### ISSUE TITLE
页面多了会不会有性能问题

### ISSUE THREAD

**Issue by skyliwq** [IVLIU/react-offscreen#1]
页面多了会不会有性能问题？

**Comment by IVLIU** [comment]
> 页面多了会不会有性能问题？

不会的，它是利用Suspense的fallback切换机制，当组件失活之后，是不会参与diff的。

**Comment by IVLIU** [comment]
![image](https://github.com/IVLIU/react-offscreen/assets/23292534/d2435d62-76b1-428d-8b38-22c799a0f477)
可以看到当child挂起的事后，Suspense将渲染fallback，对应到这里是一个空的fragment，所以基本上是没有性能开销的
@skyliwq

**Comment by cdx111** [comment]
是不是child挂起流程的时候，child的dom状态不会消失？

**Comment by cdx111** [comment]
还有为什么使用stratTranstion改变状态会导致无法隐藏？

**Comment by IVLIU** [comment]
> 是不是child挂起流程的时候，child的dom状态不会消失？

是的，当children挂起时，state和ref状态不会丢失，useEffect的销毁函数也不会执行，dom会设置为display none

**Comment by IVLIU** [comment]
> 还有为什么使用stratTranstion改变状态会导致无法隐藏？

可以提供一个复现例子吗

**Comment by IVLIU** [comment]
> 还有为什么使用stratTranstion改变状态会导致无法隐藏？

可以新提的issue我来修复下，或者可以尝试修复下

**Comment by IVLIU** [comment]
> 还有为什么使用stratTranstion改变状态会导致无法隐藏？

![image](https://github.com/IVLIU/react-offscreen/assets/23292534/e5e34425-be38-4539-927c-08955584a854)
由于react的限制，并发模式下再次挂起不会显示回退，所以建议切换为非并发模式，另外我会新增dev环境下的警告
@cdx111
