### ISSUE TITLE
卸载时为何要执行resolvePromise？

### ISSUE THREAD

**Issue by wanglufei561** [IVLIU/react-offscreen#3]
<img width="882" alt="image" src="https://github.com/IVLIU/react-offscreen/assets/106478134/ce427c1c-786a-42d1-ae97-9b3264a2c77c">
组件都要卸载了，为何还要resolvePromise？清除suspense中的记录么？还是要卸载suspense的fallback

**Comment by IVLIU** [comment]
> <img alt="image" width="882" src="https://private-user-images.githubusercontent.com/106478134/287893749-ce427c1c-786a-42d1-ae97-9b3264a2c77c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDY2MDEsIm5iZiI6MTcwMTc0NjMwMSwicGF0aCI6Ii8xMDY0NzgxMzQvMjg3ODkzNzQ5LWNlNDI3YzFjLTc4NmEtNDJkMS1hZTk3LTliMzI2NGEyYzc3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwMzE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDFmN2JhMDcyMDA3Yzk2NjkxMDYyM2VkNmE5NzQ0OGRjMzU3Yjk1MGVhNmIzZTQ3ODc2N2RjYzE0OTdhYmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5kQZHsLBx_cKrfAsTdIiCtX31jnK_QA3QEJMio-x_eg"> 组件都要卸载了，为何还要resolvePromise？清除suspense中的记录么？还是要卸载suspense的fallback

防止promise未被resolve造成内存泄漏
