### ISSUE TITLE
react-router 下无效

### ISSUE THREAD

**Issue by skyliwq** [IVLIU/react-offscreen#4]
在react-router 下使用没有效果，该如何配置大神

**Comment by IVLIU** [comment]
请问你使用的框架是什么

**Comment by skyliwq** [comment]
> 请问你使用的框架是什么

react18 antd

**Comment by IVLIU** [comment]
目前Offscreen针对的是组件，Offscreen是不能够被卸载的。
而react-router在做路由切换时，是会卸载组件的，因此无法缓存。
如果你用的是umi的话，可以参考下https://juejin.cn/post/7312304122535149604

**Comment by vaynevayne** [comment]
[tans](https://tanstack.com/router/latest) 这个router库有是否路由卸载的hook, 可以传给screen
有人在项目里使用过这个router库吗?

**Comment by IVLIU** [comment]
> [tans](https://tanstack.com/router/latest) 这个router库有是否路由卸载的hook, 可以传给screen 有人在项目里使用过这个router库吗?

可以参考下https://juejin.cn/post/7312304122535149604

**Comment by IVLIU** [comment]
> [tans](https://tanstack.com/router/latest) 这个router库有是否路由卸载的hook, 可以传给screen 有人在项目里使用过这个router库吗?

哪个hook？

**Comment by vaynevayne** [comment]
![image](https://github.com/IVLIU/react-offscreen/assets/124666577/cda8ab19-3faa-4d41-b76a-cad196347ff4)
