### ISSUE TITLE
16.8不支持吗

### ISSUE THREAD

**Issue by diyiduanfa** [IVLIU/react-offscreen#6]
16.8不支持吗

**Comment by IVLIU** [comment]
可以测试下看看

**Comment by IVLIU** [comment]
https://codesandbox.io/p/sandbox/react-16-8-forked-jw8kxf?file=%2Fsrc%2Findex.js%3A6%2C40
可以参考下这个例子

**Comment by diyiduanfa** [comment]
https://codesandbox.io/p/sandbox/react-16-8-forked-ynf9dp?file=%2Fsrc%2Findex.js.   这种情况下，大于2个的时候好像只能缓存一个
